Predicting Image From Validation Set

In [26]:
## Predicting Model


from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
import matplotlib.pyplot as plt
model = load_model('/Users/juggs/Desktop/Python/projects/Chest X-ray/model_vgg19.h5 ')
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/NORMAL/NORMAL2-IM-1427-0001.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[6.810383e-32 1.000000e+00]]


In [17]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/PNEUMONIA/person1946_bacteria_4874.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0. 1.]]


In [18]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/NORMAL/NORMAL2-IM-1430-0001.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[1.4260628e-34 1.0000000e+00]]


In [19]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/PNEUMONIA/person1946_bacteria_4875.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0. 1.]]


In [20]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/NORMAL/NORMAL2-IM-1431-0001.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[1.000000e+00 2.428727e-15]]


In [21]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/PNEUMONIA/person1947_bacteria_4876.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0. 1.]]


In [22]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/NORMAL/NORMAL2-IM-1436-0001.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[6.2001834e-04 9.9937999e-01]]


In [23]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/PNEUMONIA/person1949_bacteria_4880.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0. 1.]]


In [24]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/NORMAL/NORMAL2-IM-1437-0001.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0.14253585 0.8574642 ]]


In [25]:
img = image.load_img('/Users/juggs/Desktop/Python/projects/Chest X-ray/chest_xray dataset/val/PNEUMONIA/person1950_bacteria_4881.jpeg', target_size = (224,224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)
classes = model.predict(img_data)
print(classes)

[[0. 1.]]
